
    language: bash
    sudo: required
    install:
      - sudo apt-get install scala
    script: 
      - cd cpp && g++ -o hello hello.cpp && chmod u+x run.sh && time bash run.sh
      - cd ../java && javac hello.java && time java hello
      - cd ../scalaraw && scalac hello.scala && time scala hello
