
    language: bash
    sudo: required
    install:
      - sudo apt-get update
      - sudo find /usr -name "*libunwind*" -delete
      - sudo apt install libunwind8-dev clang
      - curl -s "https://get.sdkman.io" | bash
      - source "$HOME/.sdkman/bin/sdkman-init.sh"
      - sdk install scala 2.13.4
      - sdk install sbt
      - curl --proto '=https' --tlsv1.2 - sSf https://sh.rustup.rs | sh -s -- -y
      - rustup
    script: 
      - cd cpp && g++ -o hello hello.cpp && chmod u+x run.sh && time bash run.sh
      - cd ../java && javac hello.java && time java hello
      - cd ../scalaraw && scalac hello.scala && time scala hello
      #- cd ../scalanative && sbt run && time bash run.sh
      - cd ../rust && rustc hello.rs && time bash run.sh
